version: '3'
services:
  nginx:
    restart: always
    build: ./nginx
    depends_on: 
      - main
    ports:
      - "80:80"
    links:
      - main:main

  db:
    restart: always
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: temppass
      POSTGRES_DB: pelican
    volumes:
      - ./main/data:/var/lib/postgresql/data

  main:
    restart: always
    build: ./main
    volumes:
      - ./main:/usr/src/app/
    ports:
      - "8000:8000"
    command: /usr/local/bin/gunicorn -w 2 -b :8000 pelican:app
    depends_on:
      - db
    links:
      - celery
      - rabbitmq

  rabbitmq:
    restart: always
    image: rabbitmq
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: pelican

  celery:
    restart: always
    build: ./main
    command: "celery worker -A tasks --loglevel=info"
    user: nobody
    volumes:
        - ./main:/usr/src/app
    depends_on:
      - rabbitmq
